[tool.poetry]
name = "autocensus"
version = "2.0.0-alpha.2"
description = "A tool for collecting ACS and geospatial data from the Census API"
license = "MIT"
authors = ["Christopher Setzer <chris.setzer@socrata.com>"]
readme = "readme.md"
homepage = "https://github.com/socrata/autocensus"
keywords = ["census", "acs", "api", "data", "socrata"]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research"
]

[tool.poetry.dependencies]
python = "^3.7"
appdirs = "^1.4.3"
Fiona = "^1.8.13"
geopandas = "^0.7.0"
httpx = "^0.16.1"
importlib_metadata = {version = "^2.0.0", python = "< 3.8"}
nest-asyncio = "^1.3.2"
numpy = "^1.18.3"
pandas = ">=0.25.3, ^1.0.3"
shapely = "^1.7.0"
socrata-py = ">=0.4, ^1.0"
tenacity = "^6.1.0"
typing-extensions = "^3.7.4"
us = "^2.0.2"
yarl = "^1.4.2"

[tool.poetry.dev-dependencies]
bandit = "^1.6.2"
black = "^19.10b0"
flake8 = "^3.7.9"
isort = "^4.3.21"
mypy = "^0.770"
pydocstyle = "^5.0.2"
pytest = "^5.4.1"

[tool.black]
line-length = 99
target-version = ["py37"]
skip-string-normalization = true

[tool.isort]
force_sort_within_sections = true
include_trailing_comma = true
line_length = 99
multi_line_output = 3

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
